<%@ Page Title="" Language="C#" MasterPageFile="~/toptanci/toptanci.master" AutoEventWireup="true" CodeFile="urunlerim.aspx.cs" Inherits="toptanci_urunlerim" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
    <style type="text/css">
    .style1
    {
        width: 100%;
    }
    .style2
    {
        width: 341px;
    }
        .style3
        {
            width: 44px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <table class="style1">
    <tr>
        <td class="style3">
            &nbsp;</td>
        <td>
            <table class="style1">
                <tr>
                    <td class="style2">
                        &nbsp;</td>
                    <td>
                        <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Size="Medium" 
                            Text="Ürünlerim Sayfası"></asp:Label>
                    </td>
                    <td>
                        &nbsp;</td>
                </tr>
            </table>
        </td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style3">
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style3">
            &nbsp;</td>
        <td align="left" valign="top">
            <asp:Label ID="Label2" runat="server" Font-Bold="True" 
                Text="Henüz Ekli Ürününüz Bulunmamaktadır!"></asp:Label>

  
            <br />

  
            <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
                style="margin-left: 283px" Text="Sil" Width="63px" />

  
    <asp:GridView ID="GridView1" runat="server" PageSize="3"  
        AutoGenerateColumns="False" 
        onselectedindexchanged="GridView1_SelectedIndexChanged1" 
        DataKeyNames="urun_kod" AutoGenerateDeleteButton="False"  OnRowDeleting="GridView1_RowDeleting"  
        OnRowEditing="GridView1_RowEditing"
        OnRowUpdating="GridView1_RowUpdating"
        OnPageIndexChanging="GridView1_PageIndexChanging" 
        OnRowCancelingEdit="GridView1_RowCancelingEdit" 
        AutoGenerateEditButton="False"  
        style="margin-top: 7px; margin-left: 0px; margin-right: 58px;" Width="555px">

<Columns>
       
<asp:TemplateField HeaderText="Ürün Kodu" Visible="false">
<ItemTemplate>
<asp:Label ID="urun_kod" runat="server" Text='<%#Eval ("urun_kod")%>' Height="20"></asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Tür Kodu" Visible="false">
<ItemTemplate >
<asp:Label ID="tur_kod" runat="server" Text='<%#Eval ("tur_kod")%>' Height="20"></asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Ürün Türü">
<ItemTemplate>
<asp:Label ID="tur_ad" runat="server" Text='<%#Eval("tur_ad")%>' ReadOnly="true" Height="20"> </asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Ürün Adı">
<ItemTemplate>
<asp:Label ID="ad" runat="server" Text='<%#Eval ("ad") %>' ReadOnly="true" Height="20"></asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Miktarı(/kg)">
<ItemTemplate>
<asp:TextBox ID="miktar" runat="server" Text='<%#Eval ("miktar")%>' Width="75" Height="20"> </asp:TextBox>
</ItemTemplate>
</asp:TemplateField>
 <asp:TemplateField HeaderText="Düzenle/Sil">
        <ItemTemplate>
        <asp:ImageButton ID="edit"  AlternateText="edit" runat="server"  ImageUrl="~/image/edit.ico" CommandName="Edit" Height="20" Width="22"></asp:ImageButton>
        
    <asp:CheckBox ID="CheckBox" runat="server"  />

        </ItemTemplate>
        <EditItemTemplate>
        <asp:ImageButton ID="Update"  runat="server" ImageUrl="~/image/update.ico" CommandName="Update" Height="20" Width="22"></asp:ImageButton>
        <asp:ImageButton ID="Cancel"  runat="server" ImageUrl="~/image/cancel_edit.ico" CommandName="Cancel" Height="20" Width="22"></asp:ImageButton>
        
        </EditItemTemplate>
       
        </asp:TemplateField>
        

<asp:TemplateField >
<ItemTemplate>
 <asp:RegularExpressionValidator ID="miktarValid2" runat="server" 
                        ControlToValidate="miktar" ErrorMessage="**Gerçersiz Miktar Girdiniz" 
                        ValidationExpression="^\d+$"></asp:RegularExpressionValidator>
</ItemTemplate>
</asp:TemplateField>
</Columns>

</asp:GridView>

  
            <br />

  
        </td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style3">
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style3">
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style3">
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
</table>

  
</asp:Content>

