<%@ Page Title="" Language="C#" MasterPageFile="~/yonetici/yonetici.master" AutoEventWireup="true" CodeFile="bilgprof.aspx.cs" Inherits="yonetici_bilgprof" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
    <style type="text/css">
        .style1
        {
            width: 99%;
        }
        .style2
        {
            width: 12px;
        }
        .style3
        {
            width: 656px;
        }
        .style4
        {
            width: 12px;
            height: 18px;
        }
        .style5
        {
            width: 656px;
            height: 18px;
        }
        .style6
        {
        height: 18px;
    }
    .style7
    {
        width: 6px;
    }
    .style8
    {
        height: 18px;
        width: 6px;
    }
    .style9
    {
        width: 321px;
    }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <table class="style1">
        <tr>
            <td class="style2">
                &nbsp;</td>
            <td class="style3">
                <table class="style1">
                    <tr>
                        <td>
                            &nbsp;</td>
                        <td class="style9">
                            &nbsp;</td>
                        <td>
                            <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Size="Medium" 
                                Text="Personeler Bilgi Sayfası"></asp:Label>
                        </td>
                    </tr>
                </table>
            </td>
            <td class="style7">
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style4">
                </td>
            <td class="style5">
                
            </td>
            <td class="style8">
                </td>
            <td class="style6">
                </td>
            <td class="style6">
                </td>
            <td class="style6">
                </td>
        </tr>
        <tr>
            <td class="style2">
                &nbsp;</td>
            <td class="style3">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label3" runat="server" Font-Bold="True" 
                    Text="Sistemde Ekli Bilgisayar Profesyoneli Bulunmuyor!"></asp:Label>
            </td>
            <td class="style7">
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style2">
                &nbsp;</td>
            <td class="style3" align="center">
                
                <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
                    style="margin-left: 751px" Text="Sil" Width="35px" />
                
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
    AutoGenerateDeleteButton="False"  OnRowDeleting="GridView1_RowDeleting" 
        Width="789px" Height="78px"    >
    <Columns>
<asp:TemplateField HeaderText="kod" Visible="false">
<ItemTemplate>
<asp:Label ID="kod" runat="server" Text='<%#Eval("kod")%>' ReadOnly="true"> </asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="İsim">
<ItemTemplate>
<asp:Label ID="ad" runat="server" Text='<%#Eval("ad")%>' ReadOnly="true"> </asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Soyisim">
<ItemTemplate>
<asp:Label ID="soyad" runat="server" Text='<%#Eval ("soyad") %>' ReadOnly="true"></asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="E-mail">
<ItemTemplate>
<asp:Label ID="email" runat="server" Text='<%#Eval ("email") %>' ReadOnly="true"></asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Cep Tel">
<ItemTemplate>
<asp:Label ID="cep_tel" runat="server" Text='<%#Eval ("cep_tel")%>' ReadOnly="true"> </asp:Label>
</ItemTemplate>
</asp:TemplateField>

<asp:TemplateField HeaderText="Adres">
<ItemTemplate>
<asp:Label ID="adres" runat="server" Text='<%#Eval ("adres")%>' ReadOnly="true"> </asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Adres İlçe">
<ItemTemplate>
<asp:Label ID="adres_ilce" runat="server" Text='<%#Eval ("adres_ilce")%>' ReadOnly="true"> </asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Adres İl">
<ItemTemplate>
<asp:Label ID="adres_il" runat="server" Text='<%#Eval ("adres_il")%>' ReadOnly="true"> </asp:Label>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Ak./Pas.">
<ItemTemplate>
<asp:ImageButton ID="ap" runat="server"  AlternateText='<%#Eval ("ap")%>'   ImageUrl=""  OnClick="ap"  Height="20" Width="22"> </asp:ImageButton>
</ItemTemplate>
</asp:TemplateField>
<asp:TemplateField HeaderText="Sil">
<ItemTemplate>
<asp:CheckBox ID="CheckBox" runat="server"  />
</ItemTemplate>
</asp:TemplateField>
   
        
</Columns>
    </asp:GridView>
                <br />
            </td>
            <td class="style7">
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style2">
                &nbsp;</td>
            <td class="style3">
                &nbsp;</td>
            <td class="style7">
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
    </table>
</asp:Content>

